# Generated by Django 2.2.2 on 2020-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_project', models.CharField(max_length=255)),
                ('about_description', models.TextField()),
                ('about_image', models.ImageField(null=True, upload_to='media/about')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('slider_image', models.ImageField(null=True, upload_to='media/home')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_text', models.CharField(max_length=255)),
                ('project_titel', models.CharField(max_length=255)),
                ('project_image', models.ImageField(null=True, upload_to='media/projects')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=255)),
                ('skill_progress', models.CharField(max_length=255)),
            ],
        ),
    ]
